import { BadgeCheck, Building2, Check, ClipboardList } from "lucide-react";
import Link from "next/link";
import { requireRole } from "@/lib/auth/guards";
import { prisma } from "@/lib/db/prisma";
import { VerificationReview } from "@/components/admin/verification-review";

export default async function AdminVerificationPage() {
  await requireRole("ADMIN");
  const applications = await prisma.verificationRecord.findMany({ where: { targetType: "AGENT", status: "PENDING" }, orderBy: { createdAt: "asc" }, take: 50 });
  const agentIds = applications.map((application) => application.targetId);
  const agents = await prisma.agentProfile.findMany({ where: { id: { in: agentIds } }, include: { user: true, listings: { where: { status: "ACTIVE" }, select: { id: true } } } });
  const agentById = new Map(agents.map((agent) => [agent.id, agent]));

  return <main className="min-h-screen px-4 pb-12 pt-4 sm:px-8 lg:pl-72 lg:pr-12"><aside className="glass-nav fixed bottom-3 left-3 right-3 z-10 flex items-center justify-around p-2 lg:bottom-auto lg:left-4 lg:top-4 lg:h-[calc(100vh-2rem)] lg:w-56 lg:flex-col lg:items-stretch lg:justify-start lg:p-4"><Link className="mb-6 hidden items-center gap-2 font-semibold lg:flex" href="/"><span className="flex size-9 items-center justify-center rounded-[12px] bg-[var(--accent)] text-white"><Building2 size={19} aria-hidden="true" /></span>Nyumba Nearby</Link><Link className="flex min-h-11 items-center gap-3 rounded-[12px] bg-[var(--accent-soft)] px-3 text-sm text-[var(--accent)]" href="/admin/verification"><ClipboardList size={19} aria-hidden="true" />Verification queue</Link></aside><div className="mx-auto max-w-6xl"><header className="pb-8 pt-10"><p className="eyebrow">Trust operations</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Agent verification</h1><p className="mt-2 text-[var(--text-secondary)]">Review evidence before a profile receives the verified badge.</p></header><div className="space-y-3">{applications.length ? applications.map((application) => { const agent = agentById.get(application.targetId); return <article className="glass-surface grid gap-5 p-5 lg:grid-cols-[1fr_auto] lg:items-center" key={application.id}><div><div className="flex items-center gap-2"><BadgeCheck className="text-[var(--accent)]" size={20} aria-hidden="true" /><h2 className="text-lg font-semibold">{agent?.businessName ?? "Unknown agent"}</h2></div><p className="mt-1 text-sm text-[var(--text-secondary)]">{agent?.user.firstName} {agent?.user.lastName} · {agent?.listings.length ?? 0} active listings</p><p className="mt-4 max-w-2xl text-sm leading-6">{application.notes}</p><p className="mt-3 text-xs text-[var(--text-tertiary)]">Submitted {new Intl.DateTimeFormat("en-TZ", { dateStyle: "medium" }).format(application.createdAt)}</p></div><VerificationReview verificationId={application.id} /></article>; }) : <div className="glass-surface p-8 text-center"><Check className="mx-auto text-[var(--success)]" size={28} aria-hidden="true" /><h2 className="mt-3 font-semibold">Queue is clear</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">New verification applications will appear here.</p></div>}</div></div></main>;
}
