-- Add new fields to listings table
ALTER TABLE listings ADD COLUMN IF NOT EXISTS room_size INTEGER;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS number_of_rooms INTEGER;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS furnished BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS floor_level INTEGER;

ALTER TABLE listings ADD COLUMN IF NOT EXISTS gender_preference VARCHAR(10) NOT NULL DEFAULT 'ANY';
ALTER TABLE listings ADD COLUMN IF NOT EXISTS pets_allowed BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS smoking_allowed BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS max_tenants INTEGER;

ALTER TABLE listings ADD COLUMN IF NOT EXISTS deposit_amount INTEGER;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS utilities_included BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS lease_duration VARCHAR(50);
